export type ConstructorProfile = {
  fullTeamName?: string;
  base?: string;
  factoryAddress?: string;
  teamChief?: string;
  technicalChief?: string;
  chassis?: string;
  powerUnit?: string;
  reserveDriver?: string;
  primarySponsors?: string;
  ownership?: string;
  predecessor?: string;
  teamColors?: string;
  technicalPartners?: string;
  fanImpression?: string;
  firstTeamEntry?: string;
  grandPrixEntered?: string;
  teamPoints?: string;
  highestRaceFinish?: string;
  podiums?: string;
  highestGridPosition?: string;
  polePositions?: string;
  worldChampionships?: string;
};

const windTunnelAllowanceByPosition: Record<number, string> = {
  1: "70% 基准气动测试配额",
  2: "75% 基准气动测试配额",
  3: "80% 基准气动测试配额",
  4: "85% 基准气动测试配额",
  5: "90% 基准气动测试配额",
  6: "95% 基准气动测试配额",
  7: "100% 基准气动测试配额",
  8: "105% 基准气动测试配额",
  9: "110% 基准气动测试配额",
  10: "115% 基准气动测试配额",
};

const constructorProfiles: Record<string, ConstructorProfile> = {
  alpine: {
    fullTeamName: "BWT Alpine 一级方程式车队",
    base: "英国恩斯通",
    factoryAddress: "英国牛津郡恩斯通 Whiteways Technical Centre",
    teamChief: "弗拉维奥·布里亚托利",
    technicalChief: "大卫·桑切斯",
    chassis: "A526",
    powerUnit: "梅赛德斯",
    reserveDriver: "杰克·杜汉、保罗·阿隆、库什·迈尼",
    primarySponsors: "BWT、Castrol、Microsoft",
    ownership: "雷诺集团旗下 Alpine 品牌厂队",
    predecessor: "雷诺厂队、Benetton、Toleman 等恩斯通车队体系",
    teamColors: "蓝色、粉色、黑色",
    technicalPartners: "梅赛德斯动力单元、BWT、Castrol",
    fanImpression: "雷诺/Alpine 厂队延续，历史底蕴强，但近年表现起伏较大。",
    firstTeamEntry: "1986",
    grandPrixEntered: "395",
    teamPoints: "2016",
    highestRaceFinish: "1（21 次）",
    podiums: "60",
    highestGridPosition: "1（20 次）",
    polePositions: "20",
    worldChampionships: "2",
  },
  aston_martin: {
    fullTeamName: "阿斯顿·马丁 Aramco 一级方程式车队",
    base: "英国银石",
    factoryAddress: "英国银石 AMR Technology Campus",
    teamChief: "阿德里安·纽维",
    technicalChief: "恩里科·卡迪莱",
    chassis: "AMR26",
    powerUnit: "本田",
    reserveDriver: "杰克·克劳福德",
    primarySponsors: "Aramco、Valvoline",
    ownership: "由 Lawrence Stroll 相关投资集团控股运营",
    predecessor: "Racing Point、Force India、Jordan 车队体系",
    teamColors: "英伦赛车绿、荧光绿",
    technicalPartners: "本田动力单元、Aramco 燃料与润滑油、Valvoline",
    fanImpression: "投入规模大、设施现代化，车迷期待其从中游跃升为争冠车队。",
    firstTeamEntry: "2018",
    grandPrixEntered: "155",
    teamPoints: "863",
    highestRaceFinish: "1（1 次）",
    podiums: "12",
    highestGridPosition: "1（1 次）",
    polePositions: "1",
    worldChampionships: "0",
  },
  audi: {
    fullTeamName: "奥迪 Revolut F1 车队",
    base: "瑞士欣维尔",
    factoryAddress: "瑞士欣维尔 Sauber 赛车基地",
    teamChief: "马蒂亚·比诺托",
    technicalChief: "詹姆斯·基",
    chassis: "R26",
    powerUnit: "奥迪",
    primarySponsors: "Revolut、阿迪达斯",
    ownership: "奥迪厂队，基于 Sauber 赛车组织运营",
    predecessor: "Sauber / Stake F1 Team / Alfa Romeo 车队体系",
    teamColors: "银色、红色、黑色",
    technicalPartners: "奥迪动力单元、Revolut、阿迪达斯",
    fanImpression: "奥迪厂队身份带来高关注度，车迷更看重其中长期建设能力。",
    firstTeamEntry: "2026",
    grandPrixEntered: "3",
    teamPoints: "2",
    highestRaceFinish: "9（1 次）",
    podiums: "0",
    highestGridPosition: "9（1 次）",
    polePositions: "0",
    worldChampionships: "0",
  },
  cadillac: {
    fullTeamName: "凯迪拉克一级方程式车队",
    base: "英国银石",
    factoryAddress: "英国银石凯迪拉克 F1 基地",
    teamChief: "格雷姆·洛顿",
    technicalChief: "尼克·切斯特",
    chassis: "MAC-26",
    powerUnit: "法拉利",
    reserveDriver: "周冠宇",
    primarySponsors: "通用汽车、凯迪拉克",
    ownership: "通用汽车凯迪拉克品牌与 TWG Motorsports 相关项目",
    predecessor: "2026 新参赛车队",
    teamColors: "黑色、金色、蓝色",
    technicalPartners: "法拉利动力单元、通用汽车/凯迪拉克技术体系",
    fanImpression: "美国厂商品牌辨识度高，新军表现和长期投入是车迷关注重点。",
    firstTeamEntry: "2026",
    grandPrixEntered: "3",
    teamPoints: "0",
    highestRaceFinish: "13（1 次）",
    podiums: "0",
    highestGridPosition: "18（1 次）",
    polePositions: "0",
    worldChampionships: "0",
  },
  ferrari: {
    fullTeamName: "法拉利 HP 车队",
    base: "意大利马拉内罗",
    factoryAddress: "意大利马拉内罗 Via Abetone Inferiore 4",
    teamChief: "弗雷德里克·瓦瑟尔",
    technicalChief: "洛伊克·塞拉 / 恩里科·瓜尔蒂耶里",
    chassis: "SF-26",
    powerUnit: "法拉利",
    reserveDriver: "安东尼奥·吉奥维纳兹",
    primarySponsors: "HP、Shell、Puma、IBM",
    ownership: "法拉利公司厂队",
    predecessor: "1950 年以来持续参赛的法拉利厂队",
    teamColors: "法拉利红、白色、黄色点缀",
    technicalPartners: "法拉利动力单元、Shell 燃料与润滑油、HP 技术合作",
    fanImpression: "F1 最具标志性的车队，车迷基础庞大，胜负压力和舆论关注度都极高。",
    firstTeamEntry: "1950",
    grandPrixEntered: "1126",
    teamPoints: "10765",
    highestRaceFinish: "1（249 次）",
    podiums: "642",
    highestGridPosition: "1（254 次）",
    polePositions: "254",
    worldChampionships: "16",
  },
  haas: {
    fullTeamName: "TGR 哈斯 F1 车队",
    base: "美国坎纳波利斯",
    factoryAddress: "美国北卡罗来纳州坎纳波利斯哈斯 F1 基地",
    teamChief: "小松礼雄",
    technicalChief: "安德烈亚·德佐尔多",
    chassis: "VF-26",
    powerUnit: "法拉利",
    reserveDriver: "平川亮",
    primarySponsors: "Toyota Gazoo Racing、MoneyGram",
    ownership: "Gene Haas 创立并拥有的美国车队",
    predecessor: "2016 年新参赛车队",
    teamColors: "白色、黑色、红色",
    technicalPartners: "法拉利动力单元、Dallara 底盘/制造支持、Toyota Gazoo Racing 技术合作",
    fanImpression: "预算相对精简、运营效率受关注，常被视为中下游搅局者。",
    firstTeamEntry: "2016",
    grandPrixEntered: "217",
    teamPoints: "404",
    highestRaceFinish: "4（2 次）",
    podiums: "0",
    highestGridPosition: "4（1 次）",
    polePositions: "1",
    worldChampionships: "0",
  },
  mclaren: {
    fullTeamName: "迈凯伦 Mastercard F1 车队",
    base: "英国沃金",
    factoryAddress: "英国萨里郡沃金 McLaren Technology Centre",
    teamChief: "安德烈亚·斯特拉",
    technicalChief: "彼得·普罗德罗莫 / 尼尔·霍尔迪",
    chassis: "MCL40",
    powerUnit: "梅赛德斯",
    reserveDriver: "莱昂纳多·福纳罗利、帕托·奥沃德",
    primarySponsors: "Mastercard、OKX、Google、Cisco",
    ownership: "迈凯伦赛车公司运营，隶属迈凯伦集团体系",
    predecessor: "Bruce McLaren 创立的迈凯伦车队",
    teamColors: "木瓜橙、黑色",
    technicalPartners: "梅赛德斯动力单元、Google、Cisco、OKX",
    fanImpression: "近年复兴势头强，年轻车手组合和高效升级能力获得广泛好评。",
    firstTeamEntry: "1966",
    grandPrixEntered: "997",
    teamPoints: "7829.5",
    highestRaceFinish: "1（203 次）",
    podiums: "446",
    highestGridPosition: "1（177 次）",
    polePositions: "177",
    worldChampionships: "10",
  },
  mercedes: {
    fullTeamName: "梅赛德斯-AMG 马石油一级方程式车队",
    base: "英国布拉克利",
    factoryAddress: "英国北安普敦郡布拉克利 Mercedes-AMG F1 Operations Centre",
    teamChief: "托托·沃尔夫",
    technicalChief: "詹姆斯·艾利森",
    chassis: "W17",
    powerUnit: "梅赛德斯",
    reserveDriver: "弗雷德里克·维斯蒂",
    primarySponsors: "PETRONAS、INEOS、TeamViewer、IWC",
    ownership: "梅赛德斯-奔驰集团、Toto Wolff 与 INEOS 共同持股体系",
    predecessor: "Brawn GP、Honda、BAR、Tyrrell 车队体系",
    teamColors: "银色、黑色、青绿色",
    technicalPartners: "梅赛德斯动力单元、PETRONAS 燃料与润滑油、INEOS",
    fanImpression: "混动时代统治力深刻影响车迷认知，技术体系和执行力仍被高度评价。",
    firstTeamEntry: "1970",
    grandPrixEntered: "332",
    teamPoints: "8294.5",
    highestRaceFinish: "1（125 次）",
    podiums: "204",
    highestGridPosition: "1（139 次）",
    polePositions: "138",
    worldChampionships: "8",
  },
  racing_bulls: {
    fullTeamName: "Visa Cash App Racing Bulls 一级方程式车队",
    base: "意大利法恩扎",
    factoryAddress: "意大利艾米利亚-罗马涅大区法恩扎 Racing Bulls 基地",
    teamChief: "艾伦·珀梅恩",
    technicalChief: "蒂姆·戈斯",
    chassis: "VCARB 03",
    powerUnit: "红牛-福特",
    reserveDriver: "角田裕毅",
    primarySponsors: "Visa、Cash App、Red Bull",
    ownership: "红牛集团旗下车队",
    predecessor: "AlphaTauri、Toro Rosso、Minardi 车队体系",
    teamColors: "蓝色、白色、红色",
    technicalPartners: "红牛-福特动力单元、Visa、Cash App",
    fanImpression: "红牛体系第二车队，培养新人和与大车队技术协同是主要看点。",
    firstTeamEntry: "1985",
    grandPrixEntered: "402",
    teamPoints: "961",
    highestRaceFinish: "1（2 次）",
    podiums: "6",
    highestGridPosition: "1（1 次）",
    polePositions: "1",
    worldChampionships: "0",
  },
  rb: {
    fullTeamName: "Visa Cash App Racing Bulls 一级方程式车队",
    base: "意大利法恩扎",
    factoryAddress: "意大利艾米利亚-罗马涅大区法恩扎 Racing Bulls 基地",
    teamChief: "艾伦·珀梅恩",
    technicalChief: "蒂姆·戈斯",
    chassis: "VCARB 03",
    powerUnit: "红牛-福特",
    reserveDriver: "角田裕毅",
    primarySponsors: "Visa、Cash App、Red Bull",
    ownership: "红牛集团旗下车队",
    predecessor: "AlphaTauri、Toro Rosso、Minardi 车队体系",
    teamColors: "蓝色、白色、红色",
    technicalPartners: "红牛-福特动力单元、Visa、Cash App",
    fanImpression: "红牛体系第二车队，培养新人和与大车队技术协同是主要看点。",
    firstTeamEntry: "1985",
    grandPrixEntered: "402",
    teamPoints: "961",
    highestRaceFinish: "1（2 次）",
    podiums: "6",
    highestGridPosition: "1（1 次）",
    polePositions: "1",
    worldChampionships: "0",
  },
  red_bull: {
    fullTeamName: "甲骨文红牛车队",
    base: "英国米尔顿凯恩斯",
    factoryAddress: "英国米尔顿凯恩斯 Red Bull Technology Campus",
    teamChief: "洛朗·梅基斯",
    technicalChief: "皮埃尔·瓦谢",
    chassis: "RB22",
    powerUnit: "红牛-福特",
    primarySponsors: "Oracle、Red Bull、TAG Heuer",
    ownership: "红牛集团旗下车队",
    predecessor: "Jaguar Racing、Stewart Grand Prix 车队体系",
    teamColors: "深蓝色、红色、黄色",
    technicalPartners: "红牛-福特动力单元、Oracle、TAG Heuer",
    fanImpression: "近年冠军表现强势，技术路线和维斯塔潘时代统治力是车迷讨论焦点。",
    firstTeamEntry: "1997",
    grandPrixEntered: "421",
    teamPoints: "8304",
    highestRaceFinish: "1（130 次）",
    podiums: "233",
    highestGridPosition: "1（111 次）",
    polePositions: "111",
    worldChampionships: "6",
  },
  williams: {
    fullTeamName: "Atlassian 威廉姆斯 F1 车队",
    base: "英国格罗夫",
    factoryAddress: "英国牛津郡格罗夫 Williams Racing 基地",
    teamChief: "詹姆斯·沃尔斯",
    technicalChief: "帕特·弗莱",
    chassis: "FW48",
    powerUnit: "梅赛德斯",
    primarySponsors: "Atlassian、Gulf、Duracell、Santander",
    ownership: "Dorilton Capital 控股运营",
    predecessor: "Frank Williams 与 Patrick Head 创立的威廉姆斯车队",
    teamColors: "蓝色、白色",
    technicalPartners: "梅赛德斯动力单元、Atlassian、Gulf、Duracell",
    fanImpression: "传统豪门复兴故事吸引车迷关注，历史荣誉和现代化重建形成鲜明反差。",
    firstTeamEntry: "1978",
    grandPrixEntered: "854",
    teamPoints: "3770",
    highestRaceFinish: "1（114 次）",
    podiums: "245",
    highestGridPosition: "1（128 次）",
    polePositions: "128",
    worldChampionships: "9",
  },
};

export function getConstructorProfile(constructorId: string): ConstructorProfile {
  return constructorProfiles[constructorId] ?? {};
}

export function getWindTunnelAllowance(position: string | undefined): string | undefined {
  const positionNumber = Number(position);

  if (!Number.isInteger(positionNumber)) return undefined;

  return windTunnelAllowanceByPosition[positionNumber];
}
