export type DriverProfile = {
  debutRace?: string;
  height?: string;
  weight?: string;
  zodiacSign?: string;
  nickname?: string;
  tCamColor?: string;
  salary?: string;
  contractStatus?: string;
  superLicencePenaltyPoints?: string;
  penaltyPointsPeriod?: string;
  birthPlace?: string;
  residence?: string;
  maritalStatus?: string;
  partner?: string;
  familyAndFriends?: string;
  fanImpression?: string;
  signatureImageUrl?: string;
  grandPrixEntered?: string;
  careerPoints?: string;
  highestRaceFinish?: string;
  podiums?: string;
  highestGridPosition?: string;
  polePositions?: string;
  worldChampionships?: string;
  dnfs?: string;
};

const driverProfiles: Record<string, DriverProfile> = {
  albon: {
    debutRace: "2019 澳大利亚大奖赛",
    height: "186 cm",
    weight: "74 kg",
    nickname: "泰国小王子",
    tCamColor: "黑色",
    salary: "约 1200 万美元",
    contractStatus: "威廉姆斯长期合同",
    superLicencePenaltyPoints: "0",
    penaltyPointsPeriod: "2025-04-29 至 2026-04-29",
    birthPlace: "英国伦敦",
    residence: "摩纳哥",
    maritalStatus: "未婚(有公开伴侣)",
    partner: "Lily Muni He",
    familyAndFriends: "父亲 Nigel Albon；母亲 Kankamol Albon；朋友/教父：未公开",
    grandPrixEntered: "131",
    careerPoints: "313",
    highestRaceFinish: "3(2 次)",
    podiums: "2",
    highestGridPosition: "4(5 次)",
    polePositions: "0",
    worldChampionships: "0",
    dnfs: "22",
    fanImpression: "稳定、轮胎管理好，擅长在中下游赛车中拿分",
    signatureImageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e9/AlexanderAlbonSignature.png",
  },
  alonso: {
    debutRace: "2001 澳大利亚大奖赛",
    height: "171 cm",
    weight: "68 kg",
    nickname: "头哥",
    tCamColor: "黄色",
    salary: "约 2000 万美元",
    contractStatus: "阿斯顿·马丁合同至 2026 年底",
    superLicencePenaltyPoints: "0",
    penaltyPointsPeriod: "2025-04-29 至 2026-04-29",
    birthPlace: "西班牙奥维耶多",
    residence: "瑞士",
    maritalStatus: "曾婚(2026 年公开伴侣)",
    partner: "Melissa Jiménez",
    familyAndFriends: "父亲 José Luis Alonso；母亲 Ana Díaz；姐姐 Lorena；朋友/教父：未公开",
    grandPrixEntered: "430",
    careerPoints: "2393",
    highestRaceFinish: "1(32 次)",
    podiums: "106",
    highestGridPosition: "1(22 次)",
    polePositions: "22",
    worldChampionships: "2",
    dnfs: "85",
    fanImpression: "经验丰富、比赛阅读能力强，防守和策略执行突出",
    signatureImageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/74/FernandoAlonsoSignature.svg",
  },
  antonelli: {
    debutRace: "2025 澳大利亚大奖赛",
    height: "172 cm",
    weight: "67 kg",
    nickname: "小安东内利",
    tCamColor: "黄色",
    salary: "约 200 万美元",
    contractStatus: "梅赛德斯多年培养体系车手",
    superLicencePenaltyPoints: "0",
    penaltyPointsPeriod: "2025-04-29 至 2026-04-29",
    birthPlace: "意大利博洛尼亚",
    residence: "意大利博洛尼亚",
    maritalStatus: "未公开",
    partner: "未公开",
    familyAndFriends: "父亲 Marco Antonelli；导师 Toto Wolff；Prema 青训背景",
    grandPrixEntered: "27",
    careerPoints: "222",
    highestRaceFinish: "1(2 次)",
    podiums: "6",
    highestGridPosition: "1(2 次)",
    polePositions: "2",
    worldChampionships: "0",
    dnfs: "4",
    fanImpression: "梅赛德斯青训出身，速度快、潜力高",
  },
  arvid_lindblad: {
    debutRace: "2026 赛季首秀",
    height: "未公开",
    weight: "未公开",
    nickname: "林德布拉德",
    tCamColor: "黑色",
    salary: "约 50–100 万美元",
    contractStatus: "红牛青训体系车手",
    superLicencePenaltyPoints: "0",
    penaltyPointsPeriod: "2025-04-29 至 2026-04-29",
    birthPlace: "英国伦敦",
    residence: "英国",
    maritalStatus: "未公开",
    partner: "未公开",
    familyAndFriends: "父亲为瑞典裔，母亲为印度裔；朋友/教父：未公开",
    grandPrixEntered: "3",
    careerPoints: "4",
    highestRaceFinish: "8(1 次)",
    podiums: "0",
    highestGridPosition: "9(1 次)",
    polePositions: "0",
    worldChampionships: "0",
    dnfs: "0",
    fanImpression: "红牛青训车手，青年赛事表现受到关注",
  },
  bearman: {
    debutRace: "2024 沙特阿拉伯大奖赛",
    height: "184 cm",
    weight: "70 kg",
    nickname: "小熊人",
    tCamColor: "黄色",
    salary: "约 100 万美元",
    contractStatus: "哈斯正式车手，法拉利青训背景",
    superLicencePenaltyPoints: "0",
    penaltyPointsPeriod: "2025-04-29 至 2026-04-29",
    birthPlace: "英国切姆斯福德",
    residence: "英国",
    maritalStatus: "未婚(有公开伴侣)",
    partner: "Estelle Ogilvy",
    familyAndFriends: "父亲 David Bearman；母亲 Terri Bearman；弟弟 Thomas；朋友/教父：未公开",
    grandPrixEntered: "30",
    careerPoints: "65",
    highestRaceFinish: "4(1 次)",
    podiums: "0",
    highestGridPosition: "8(2 次)",
    polePositions: "0",
    worldChampionships: "0",
    dnfs: "4",
    fanImpression: "临场适应快，新秀首秀表现成熟",
  },
  bortoleto: {
    debutRace: "2025 澳大利亚大奖赛",
    height: "184 cm",
    weight: "72 kg",
    nickname: "博托莱托",
    tCamColor: "黄色",
    salary: "约 200 万美元",
    contractStatus: "索伯/奥迪项目正式车手",
    superLicencePenaltyPoints: "0",
    penaltyPointsPeriod: "2025-04-29 至 2026-04-29",
    birthPlace: "巴西圣保罗",
    residence: "巴西圣保罗",
    maritalStatus: "未公开",
    partner: "未公开",
    familyAndFriends: "A14 Management 旗下车手；导师 Fernando Alonso；朋友/教父：未公开",
    grandPrixEntered: "27",
    careerPoints: "21",
    highestRaceFinish: "6(1 次)",
    podiums: "0",
    highestGridPosition: "7(3 次)",
    polePositions: "0",
    worldChampionships: "0",
    dnfs: "5",
    fanImpression: "青年方程式冠军出身，节奏稳定",
  },
  bottas: {
    debutRace: "2013 澳大利亚大奖赛",
    height: "173 cm",
    weight: "69 kg",
    nickname: "博塔斯",
    tCamColor: "黄色",
    salary: "约 500 万美元",
    contractStatus: "梅赛德斯储备车手",
    superLicencePenaltyPoints: "0",
    penaltyPointsPeriod: "2025-04-29 至 2026-04-29",
    birthPlace: "芬兰纳斯托拉",
    residence: "摩纳哥",
    maritalStatus: "未婚(有公开伴侣)",
    partner: "Tiffany Cromwell",
    familyAndFriends: "父亲 Rauno Bottas；母亲 Marianne Välimaa；朋友/教父：未公开",
    grandPrixEntered: "249",
    careerPoints: "1797",
    highestRaceFinish: "1(10 次)",
    podiums: "67",
    highestGridPosition: "1(20 次)",
    polePositions: "20",
    worldChampionships: "0",
    dnfs: "29",
    fanImpression: "排位速度强，风格稳健",
  },
  colapinto: {
    debutRace: "2024 意大利大奖赛",
    height: "175 cm",
    weight: "71 kg",
    nickname: "科拉平托",
    tCamColor: "黄色",
    salary: "约 50–100 万美元",
    contractStatus: "阿尔派体系车手",
    superLicencePenaltyPoints: "0",
    penaltyPointsPeriod: "2025-04-29 至 2026-04-29",
    birthPlace: "阿根廷布宜诺斯艾利斯",
    residence: "西班牙马德里",
    maritalStatus: "未公开",
    partner: "未公开",
    familyAndFriends: "阿根廷赛车家庭支持体系；朋友/教父：未公开",
    grandPrixEntered: "30",
    careerPoints: "6",
    highestRaceFinish: "8(1 次)",
    podiums: "0",
    highestGridPosition: "8(1 次)",
    polePositions: "0",
    worldChampionships: "0",
    dnfs: "3",
    fanImpression: "阿根廷车迷支持度高，进步速度快",
  },
  gasly: {
    debutRace: "2017 马来西亚大奖赛",
    height: "177 cm",
    weight: "70 kg",
    nickname: "加大师",
    tCamColor: "黑色",
    salary: "约 1200 万美元",
    contractStatus: "阿尔派合同至 2026 年底",
    superLicencePenaltyPoints: "2",
    penaltyPointsPeriod: "2025-04-29 至 2026-04-29",
    birthPlace: "法国鲁昂",
    residence: "意大利米兰",
    maritalStatus: "未婚(有公开伴侣)",
    partner: "Francisca Cerqueira Gomes",
    familyAndFriends: "父亲 Jean-Jacques Gasly；母亲 Pascale Gasly；好友 Charles Leclerc",
    grandPrixEntered: "180",
    careerPoints: "473",
    highestRaceFinish: "1(1 次)",
    podiums: "5",
    highestGridPosition: "2(1 次)",
    polePositions: "0",
    worldChampionships: "0",
    dnfs: "26",
    fanImpression: "单圈速度强，逆境中韧性突出",
  },
  hadjar: {
    debutRace: "2025 澳大利亚大奖赛",
    height: "167 cm",
    weight: "65 kg",
    nickname: "哈贾尔",
    tCamColor: "黄色",
    salary: "约 500 万美元",
    contractStatus: "红牛体系正式车手",
    superLicencePenaltyPoints: "0",
    penaltyPointsPeriod: "2025-04-29 至 2026-04-29",
    birthPlace: "法国巴黎",
    residence: "法国巴黎",
    maritalStatus: "未公开",
    partner: "未公开",
    familyAndFriends: "阿尔及利亚裔法国车手；朋友/教父：未公开",
    grandPrixEntered: "26",
    careerPoints: "55",
    highestRaceFinish: "3(1 次)",
    podiums: "1",
    highestGridPosition: "3(1 次)",
    polePositions: "0",
    worldChampionships: "0",
    dnfs: "3",
    fanImpression: "红牛体系新秀，驾驶风格积极",
  },
  hamilton: {
    debutRace: "2007 澳大利亚大奖赛",
    height: "174 cm",
    weight: "73 kg",
    nickname: "爵士",
    tCamColor: "黄色",
    salary: "约 6000 万美元",
    contractStatus: "法拉利多年合同",
    superLicencePenaltyPoints: "2",
    penaltyPointsPeriod: "2025-04-29 至 2026-04-29",
    birthPlace: "英国斯蒂夫尼奇",
    residence: "摩纳哥",
    maritalStatus: "未公开",
    partner: "未公开",
    familyAndFriends: "父亲 Anthony Hamilton；母亲 Carmen Larbalestier；弟弟 Nicolas；教父/好友：未公开",
    grandPrixEntered: "383",
    careerPoints: "5059.5",
    highestRaceFinish: "1(105 次)",
    podiums: "203",
    highestGridPosition: "1(104 次)",
    polePositions: "104",
    worldChampionships: "7",
    dnfs: "34",
    fanImpression: "七届世界冠军，排位、雨战和轮胎管理能力顶级",
  },
  hulkenberg: {
    debutRace: "2010 巴林大奖赛",
    height: "184 cm",
    weight: "78 kg",
    nickname: "绿巨人",
    tCamColor: "黑色",
    salary: "约 700 万美元",
    contractStatus: "索伯/奥迪项目多年合同",
    superLicencePenaltyPoints: "0",
    penaltyPointsPeriod: "2025-04-29 至 2026-04-29",
    birthPlace: "德国埃默里希",
    residence: "摩纳哥",
    maritalStatus: "已婚",
    partner: "Egle Ruskyte",
    familyAndFriends: "妻子 Egle Ruskyte；育有一女；朋友/教父：未公开",
    grandPrixEntered: "254",
    careerPoints: "622",
    highestRaceFinish: "3(1 次)",
    podiums: "1",
    highestGridPosition: "1(1 次)",
    polePositions: "1",
    worldChampionships: "0",
    dnfs: "44",
    fanImpression: "经验丰富、稳定可靠，常被认为正赛执行力强",
  },
  lawson: {
    debutRace: "2023 荷兰大奖赛",
    height: "174 cm",
    weight: "72 kg",
    nickname: "劳森",
    tCamColor: "黄色",
    salary: "约 100 万美元",
    contractStatus: "红牛体系车手",
    superLicencePenaltyPoints: "0",
    penaltyPointsPeriod: "2025-04-29 至 2026-04-29",
    birthPlace: "新西兰黑斯廷斯",
    residence: "新西兰",
    maritalStatus: "未公开",
    partner: "未公开",
    familyAndFriends: "新西兰赛车青训背景；朋友/教父：未公开",
    grandPrixEntered: "38",
    careerPoints: "54",
    highestRaceFinish: "5(1 次)",
    podiums: "0",
    highestGridPosition: "3(1 次)",
    polePositions: "0",
    worldChampionships: "0",
    dnfs: "6",
    fanImpression: "替补上场表现冷静，竞争风格强硬",
  },
  leclerc: {
    debutRace: "2018 澳大利亚大奖赛",
    height: "180 cm",
    weight: "69 kg",
    nickname: "乐扣",
    tCamColor: "黑色",
    salary: "约 3400 万美元",
    contractStatus: "法拉利长期合同",
    superLicencePenaltyPoints: "0",
    penaltyPointsPeriod: "2025-04-29 至 2026-04-29",
    birthPlace: "摩纳哥蒙特卡洛",
    residence: "摩纳哥",
    maritalStatus: "未婚(有公开伴侣)",
    partner: "Alexandra Saint Mleux",
    familyAndFriends: "父亲 Hervé Leclerc；哥哥 Lorenzo；弟弟 Arthur；教父 Jules Bianchi；好友 Pierre Gasly",
    grandPrixEntered: "174",
    careerPoints: "1721",
    highestRaceFinish: "1(8 次)",
    podiums: "52",
    highestGridPosition: "1(27 次)",
    polePositions: "27",
    worldChampionships: "0",
    dnfs: "23",
    fanImpression: "单圈速度顶级，法拉利核心车手之一",
    signatureImageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/72/Charles_Leclerc_F1-driver_signature.png",
  },
  max_verstappen: {
    debutRace: "2015 澳大利亚大奖赛",
    height: "181 cm",
    weight: "72 kg",
    nickname: "潘子",
    tCamColor: "黑色",
    salary: "约 7000 万美元",
    contractStatus: "红牛合同至 2028 年底",
    superLicencePenaltyPoints: "8",
    penaltyPointsPeriod: "2025-04-29 至 2026-04-29",
    birthPlace: "比利时哈瑟尔特",
    residence: "摩纳哥",
    maritalStatus: "未婚(有公开伴侣)",
    partner: "Kelly Piquet",
    familyAndFriends: "父亲 Jos Verstappen；母亲 Sophie Kumpen；好友 Lando Norris；教父：未公开",
    grandPrixEntered: "236",
    careerPoints: "3456.5",
    highestRaceFinish: "1(71 次)",
    podiums: "127",
    highestGridPosition: "1(48 次)",
    polePositions: "48",
    worldChampionships: "4",
    dnfs: "34",
    fanImpression: "进攻性强、比赛控制力顶级，连续冠军时期统治力突出",
    signatureImageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3b/MaxVerstappenSignature.png",
  },
  norris: {
    debutRace: "2019 澳大利亚大奖赛",
    height: "170 cm",
    weight: "68 kg",
    nickname: "诺里斯",
    tCamColor: "黄色",
    salary: "约 3000 万美元",
    contractStatus: "迈凯伦长期合同",
    superLicencePenaltyPoints: "0",
    penaltyPointsPeriod: "2025-04-29 至 2026-04-29",
    birthPlace: "英国布里斯托尔",
    residence: "摩纳哥",
    maritalStatus: "未公开",
    partner: "未公开",
    familyAndFriends: "父亲 Adam Norris；母亲 Cisca Norris；好友 Max Verstappen、Carlos Sainz",
    grandPrixEntered: "155",
    careerPoints: "1455",
    highestRaceFinish: "1(11 次)",
    podiums: "44",
    highestGridPosition: "1(16 次)",
    polePositions: "16",
    worldChampionships: "1",
    dnfs: "13",
    fanImpression: "人气高、单圈速度强，社交媒体形象活跃",
  },
  ocon: {
    debutRace: "2016 比利时大奖赛",
    height: "186 cm",
    weight: "66 kg",
    nickname: "奥康",
    tCamColor: "黑色",
    salary: "约 700 万美元",
    contractStatus: "哈斯多年合同",
    superLicencePenaltyPoints: "0",
    penaltyPointsPeriod: "2025-04-29 至 2026-04-29",
    birthPlace: "法国诺曼底埃夫勒",
    residence: "摩纳哥",
    maritalStatus: "未婚(有公开伴侣)",
    partner: "Elena Berri",
    familyAndFriends: "父亲 Laurent Ocon；母亲 Sabrina Ocon；朋友/教父：未公开",
    grandPrixEntered: "183",
    careerPoints: "484",
    highestRaceFinish: "1(1 次)",
    podiums: "4",
    highestGridPosition: "3(3 次)",
    polePositions: "0",
    worldChampionships: "0",
    dnfs: "25",
    fanImpression: "防守强硬，比赛对抗性强",
  },
  perez: {
    debutRace: "2011 澳大利亚大奖赛",
    height: "173 cm",
    weight: "63 kg",
    nickname: "佩大师",
    tCamColor: "黑色",
    salary: "约 800 万美元",
    contractStatus: "离开红牛后暂无正式 F1 席位",
    superLicencePenaltyPoints: "0",
    penaltyPointsPeriod: "2025-04-29 至 2026-04-29",
    birthPlace: "墨西哥瓜达拉哈拉",
    residence: "墨西哥瓜达拉哈拉",
    maritalStatus: "已婚",
    partner: "Carola Martínez",
    familyAndFriends: "妻子 Carola Martínez；哥哥 Antonio Pérez；朋友/教父：未公开",
    grandPrixEntered: "284",
    careerPoints: "1638",
    highestRaceFinish: "1(6 次)",
    podiums: "39",
    highestGridPosition: "1(3 次)",
    polePositions: "3",
    worldChampionships: "0",
    dnfs: "39",
    fanImpression: "轮胎管理突出，街道赛和逆境追击能力强",
  },
  piastri: {
    debutRace: "2023 巴林大奖赛",
    height: "178 cm",
    weight: "68 kg",
    nickname: "皮亚",
    tCamColor: "黑色",
    salary: "约 1300 万美元",
    contractStatus: "迈凯伦合同至 2026 年底",
    superLicencePenaltyPoints: "0",
    penaltyPointsPeriod: "2025-04-29 至 2026-04-29",
    birthPlace: "澳大利亚维多利亚州墨尔本",
    residence: "英国",
    maritalStatus: "未婚(有公开伴侣)",
    partner: "Lily Zneimer",
    familyAndFriends: "父亲 Chris Piastri；母亲 Nicole Piastri；经纪人 Mark Webber；朋友/教父：未公开",
    grandPrixEntered: "73",
    careerPoints: "820",
    highestRaceFinish: "1(9 次)",
    podiums: "27",
    highestGridPosition: "1(6 次)",
    polePositions: "6",
    worldChampionships: "0",
    dnfs: "4",
    fanImpression: "冷静、高效，青年赛事履历强",
  },
  russell: {
    debutRace: "2019 澳大利亚大奖赛",
    height: "185 cm",
    weight: "70 kg",
    nickname: "拉塞尔",
    tCamColor: "黑色",
    salary: "约 3400 万美元",
    contractStatus: "梅赛德斯正式车手",
    superLicencePenaltyPoints: "0",
    penaltyPointsPeriod: "2025-04-29 至 2026-04-29",
    birthPlace: "英国金斯林",
    residence: "摩纳哥",
    maritalStatus: "未婚(有公开伴侣)",
    partner: "Carmen Montero Mundt",
    familyAndFriends: "父亲 Steve Russell；母亲 Alison Russell；朋友 Alex Albon、Lando Norris",
    grandPrixEntered: "155",
    careerPoints: "1096",
    highestRaceFinish: "1(6 次)",
    podiums: "26",
    highestGridPosition: "1(9 次)",
    polePositions: "8",
    worldChampionships: "0",
    dnfs: "19",
    fanImpression: "排位速度快，技术反馈能力强",
  },
  sainz: {
    debutRace: "2015 澳大利亚大奖赛",
    height: "178 cm",
    weight: "66 kg",
    nickname: "赛恩斯",
    tCamColor: "黄色",
    salary: "约 1300 万美元",
    contractStatus: "威廉姆斯多年合同",
    superLicencePenaltyPoints: "0",
    penaltyPointsPeriod: "2025-04-29 至 2026-04-29",
    birthPlace: "西班牙马德里",
    residence: "西班牙马德里",
    maritalStatus: "未婚(有公开伴侣)",
    partner: "Rebecca Donaldson",
    familyAndFriends: "父亲 Carlos Sainz Sr.；母亲 Reyes Vázquez de Castro；好友 Lando Norris",
    grandPrixEntered: "233",
    careerPoints: "1338.5",
    highestRaceFinish: "1(4 次)",
    podiums: "29",
    highestGridPosition: "1(6 次)",
    polePositions: "6",
    worldChampionships: "0",
    dnfs: "42",
    fanImpression: "稳定全面，策略执行和比赛节奏控制出色",
  },
  stroll: {
    debutRace: "2017 澳大利亚大奖赛",
    height: "182 cm",
    weight: "70 kg",
    nickname: "少爷",
    tCamColor: "黑色",
    salary: "约 1200 万美元",
    contractStatus: "阿斯顿·马丁正式车手",
    superLicencePenaltyPoints: "0",
    penaltyPointsPeriod: "2025-04-29 至 2026-04-29",
    birthPlace: "加拿大蒙特利尔",
    residence: "瑞士日内瓦",
    maritalStatus: "未公开",
    partner: "未公开",
    familyAndFriends: "父亲 Lawrence Stroll；姐姐 Chloe Stroll；朋友/教父：未公开",
    grandPrixEntered: "193",
    careerPoints: "325",
    highestRaceFinish: "3(3 次)",
    podiums: "3",
    highestGridPosition: "1(1 次)",
    polePositions: "1",
    worldChampionships: "0",
    dnfs: "33",
    fanImpression: "起步和湿地表现有亮点，防守直接",
  },
};

export function getDriverProfile(driverId: string): DriverProfile {
  return driverProfiles[driverId] ?? {};
}

export function getZodiacSign(dateOfBirth: string): string | undefined {
  const [, monthValue, dayValue] = dateOfBirth.match(/^(\d{4})-(\d{2})-(\d{2})$/) ?? [];
  const month = Number(monthValue);
  const day = Number(dayValue);

  if (!month || !day) return undefined;

  if ((month === 3 && day >= 21) || (month === 4 && day <= 19)) return "白羊座";
  if ((month === 4 && day >= 20) || (month === 5 && day <= 20)) return "金牛座";
  if ((month === 5 && day >= 21) || (month === 6 && day <= 21)) return "双子座";
  if ((month === 6 && day >= 22) || (month === 7 && day <= 22)) return "巨蟹座";
  if ((month === 7 && day >= 23) || (month === 8 && day <= 22)) return "狮子座";
  if ((month === 8 && day >= 23) || (month === 9 && day <= 22)) return "处女座";
  if ((month === 9 && day >= 23) || (month === 10 && day <= 23)) return "天秤座";
  if ((month === 10 && day >= 24) || (month === 11 && day <= 22)) return "天蝎座";
  if ((month === 11 && day >= 23) || (month === 12 && day <= 21)) return "射手座";
  if ((month === 12 && day >= 22) || (month === 1 && day <= 19)) return "摩羯座";
  if ((month === 1 && day >= 20) || (month === 2 && day <= 18)) return "水瓶座";
  return "双鱼座";
}
